In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./dataset.csv').drop('index',axis=1)
df.head()

having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0                          -1              1                   1   
1                           1              1                   1   
2                           1              0                   1   
3                           1              0                   1   
4                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  Favicon  \
0                 -1              -1                           -1        1   
1                  0               1                           -1        1   
2                 -1              -1                           -1        1   
3                 -1              -1                            1        1   
4                  1               1                           -1        1   

   ...  popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0  ...            1       1             -1         -1           -1         -1   
1  ...            1       1             -1         -1            0         -1   
2  ...            1       1              1         -1            1         -1   
3  ...            1       1             -1         -1            1         -1   
4  ...           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 31 columns]

1 - Legitimate
0 - Suspicious
-1 - Phishing

In [3]:
df['Result'].unique()

array([-1,  1])

In [4]:
print(df.shape)
df.columns

(11055, 31)


Index(['having_IPhaving_IP_Address', 'URLURL_Length', 'Shortining_Service',
       'having_At_Symbol', 'double_slash_redirecting', 'Prefix_Suffix',
       'having_Sub_Domain', 'SSLfinal_State', 'Domain_registeration_length',
       'Favicon', 'port', 'HTTPS_token', 'Request_URL', 'URL_of_Anchor',
       'Links_in_tags', 'SFH', 'Submitting_to_email', 'Abnormal_URL',
       'Redirect', 'on_mouseover', 'RightClick', 'popUpWidnow', 'Iframe',
       'age_of_domain', 'DNSRecord', 'web_traffic', 'Page_Rank',
       'Google_Index', 'Links_pointing_to_page', 'Statistical_report',
       'Result'],
      dtype='object')

In [5]:
df.isnull().sum()

having_IPhaving_IP_Address     0
URLURL_Length                  0
Shortining_Service             0
having_At_Symbol               0
double_slash_redirecting       0
Prefix_Suffix                  0
having_Sub_Domain              0
SSLfinal_State                 0
Domain_registeration_length    0
Favicon                        0
port                           0
HTTPS_token                    0
Request_URL                    0
URL_of_Anchor                  0
Links_in_tags                  0
SFH                            0
Submitting_to_email            0
Abnormal_URL                   0
Redirect                       0
on_mouseover                   0
RightClick                     0
popUpWidnow                    0
Iframe                         0
age_of_domain                  0
DNSRecord                      0
web_traffic                    0
Page_Rank                      0
Google_Index                   0
Links_pointing_to_page         0
Statistical_report             0
Result    

In [6]:
df1=df.iloc[:,[0,1,2,3,4,5,6,8,11,16,18,22,23,25,30]]
df1.head()

having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0                          -1              1                   1   
1                           1              1                   1   
2                           1              0                   1   
3                           1              0                   1   
4                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  Domain_registeration_length  HTTPS_token  \
0                 -1                           -1           -1   
1                  0                           -1           -1   
2                 -1                           -1           -1   
3                 -1                            1           -1   
4                  1                           -1            1   

   Submitting_to_email  Redirect  Iframe  age_of_domain  web_traffic  Result  
0                   -1         0       1             -1           -1      -1  
1                    1         0       1             -1            0      -1  
2                   -1         0       1              1            1      -1  
3                    1         0       1             -1            1      -1  
4                    1         0       1             -1            0       1

In [7]:
# from skrules import SkopeRules
from sklearn.model_selection import train_test_split

In [8]:
X=df1.drop("Result",axis=1)
X.head()

having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0                          -1              1                   1   
1                           1              1                   1   
2                           1              0                   1   
3                           1              0                   1   
4                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  Domain_registeration_length  HTTPS_token  \
0                 -1                           -1           -1   
1                  0                           -1           -1   
2                 -1                           -1           -1   
3                 -1                            1           -1   
4                  1                           -1            1   

   Submitting_to_email  Redirect  Iframe  age_of_domain  web_traffic  
0                   -1         0       1             -1           -1  
1                    1         0       1             -1            0  
2                   -1         0       1              1            1  
3                    1         0       1             -1            1  
4                    1         0       1             -1            0

In [9]:
y=df1["Result"]
y

0       -1
1       -1
2       -1
3       -1
4        1
        ..
11050    1
11051   -1
11052   -1
11053   -1
11054   -1
Name: Result, Length: 11055, dtype: int64

In [10]:
y.value_counts()

 1    6157
-1    4898
Name: Result, dtype: int64

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [13]:
from sklearn.tree import DecisionTreeClassifier 
dtree_model = DecisionTreeClassifier(max_depth = 12).fit(X_train, y_train) 
predictions = dtree_model.predict(X_test)
predictions_tr = dtree_model.predict(X_train)
print('test:',confusion_matrix(y_test, predictions))
print('test:',accuracy_score(y_test,predictions))
print('train:',confusion_matrix(y_train,predictions_tr))
print('train:',accuracy_score(y_train,predictions_tr))
print(classification_report(y_test,predictions ))

test: [[1252  313]
 [ 278 1806]]
test: 0.838037818580433
train: [[2740  593]
 [ 431 3642]]
train: 0.8617337294085876
              precision    recall  f1-score   support

          -1       0.82      0.80      0.81      1565
           1       0.85      0.87      0.86      2084

    accuracy                           0.84      3649
   macro avg       0.84      0.83      0.83      3649
weighted avg       0.84      0.84      0.84      3649



In [14]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 20, max_depth=10,max_features='auto')
rfc.fit(X_train, y_train)
predictions =rfc.predict(X_test)
predictions_tr = rfc.predict(X_train)
print('test:\n',confusion_matrix(y_test, predictions))
print('test:',accuracy_score(y_test,predictions))
print('train:\n',confusion_matrix(y_train,predictions_tr))
print('train:',accuracy_score(y_train,predictions_tr))
print(classification_report(y_test,predictions ))

/home/kokurou/.local/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


test:
 [[1240  325]
 [ 274 1810]]
test: 0.8358454371060564
train:
 [[2687  646]
 [ 444 3629]]
train: 0.8528220361868755
              precision    recall  f1-score   support

          -1       0.82      0.79      0.81      1565
           1       0.85      0.87      0.86      2084

    accuracy                           0.84      3649
   macro avg       0.83      0.83      0.83      3649
weighted avg       0.84      0.84      0.84      3649



In [15]:
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 5).fit(X_train, y_train) 
predictions =knn.predict(X_test)
predictions_tr = knn.predict(X_train)
print('test:\n',confusion_matrix(y_test, predictions))
print('test:',accuracy_score(y_test,predictions))
print('train:\n',confusion_matrix(y_train,predictions_tr))
print('train:',accuracy_score(y_train,predictions_tr))
print(classification_report(y_test,predictions ))

test:
 [[1220  345]
 [ 335 1749]]
test: 0.813647574677994
train:
 [[2669  664]
 [ 529 3544]]
train: 0.8389143937348096
              precision    recall  f1-score   support

          -1       0.78      0.78      0.78      1565
           1       0.84      0.84      0.84      2084

    accuracy                           0.81      3649
   macro avg       0.81      0.81      0.81      3649
weighted avg       0.81      0.81      0.81      3649



In [16]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(n_estimators=50, learning_rate=0.1,max_depth=8, random_state=0).fit(X_train, y_train)
predictions =gbc.predict(X_test)
predictions_tr = gbc.predict(X_train)
print('test:\n',confusion_matrix(y_test, predictions))
print('test:',accuracy_score(y_test,predictions))
print('train:\n',confusion_matrix(y_train,predictions_tr))
print('train:',accuracy_score(y_train,predictions_tr))
print(classification_report(y_test,predictions ))

test:
 [[1265  300]
 [ 258 1826]]
test: 0.8470813921622362
train:
 [[2742  591]
 [ 409 3664]]
train: 0.8649743451255738
              precision    recall  f1-score   support

          -1       0.83      0.81      0.82      1565
           1       0.86      0.88      0.87      2084

    accuracy                           0.85      3649
   macro avg       0.84      0.84      0.84      3649
weighted avg       0.85      0.85      0.85      3649



In [17]:
import joblib
filename = '../api-files/gbc.pkl'
joblib.dump(gbc, filename)

['../api-files/gbc.pkl']

In [18]:
loaded_model = joblib.load(filename)
result = loaded_model.score(X_test, y_test)
print(result)

0.8470813921622362
